name: Run Cypress Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1,4"
  push:
    branches: [main, develop, feature/my-feature]
  pull_request:
    branches: [main, develop, feature/my-feature]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    services:
      jdhistory:
        image: c2dhunilu/journal-of-digital-history:latest
        ports:
          - 5173:5173
        options: >-
          --health-cmd="curl -f http://localhost:5173 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Wait for app to be ready
        run: |
          for i in {1..30}; do
            nc -z localhost 5173 && echo "App is up!" && break
            echo "Waiting for app..."
            sleep 2
          done

      - name: Run Cypress tests
        env:
          CYPRESS_BASE_URL: http://localhost:5173/
        run: yarn cy:run
