name: Run Cypress Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1,4"
  push:
    branches: [main, develop, feature/my-feature]
  pull_request:
    branches: [main, develop, feature/my-feature]

jobs:
  cypress-run:
    runs-on: self-hosted
    container:
      image: cypress/included:14.3.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Cypress tests
        env:
          CYPRESS_BASE_URL: http://10.240.4.198/
        run: cypress run
