name: Run Cypress Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1,2,3,4,5"
  push:
    branches: [main, develop, feature/my-feature]
  pull_request:
    branches: [main, develop, feature/my-feature]

jobs:
  cypress-run:
    runs-on: self-hosted
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    container:
      image: cypress/included
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Yarn 4 (Berry)
        run: corepack enable && corepack prepare yarn@4.12.0 --activate

      - name: Install dependencies
        run: yarn install

      - name: Run Cypress tests
        env:
          CYPRESS_BASE_URL: http://10.240.4.198/
        run: cypress run

      - uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          config: .github/config/slack.yml
          channel: "#jdh-cypress-test"
        if: always()
